### Login a user
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email": "alon@gmail.com",
    "password": "1234"
}

### Create a project
POST http://localhost:3001/project
Content-Type: application/json

{
    "name": "Best Project"
}

### Get user projects
GET http://localhost:3001/project

### Get user project by id
GET http://localhost:3001/project/6245b7ed07da71cc2857f6f6

### Update user project by id
PUT http://localhost:3001/project/6245b7ed07da71cc2857f6f6
Content-Type: application/json

{
    "toDo": [
        {
            "name": "Task 1",
            "priority": 1
        }
    ]
}

### Delete user project by id
DELETE http://localhost:3001/project/6245af6bade0244cf9613da2